USE [unitunes]
GO

/****** Object:  Table [dbo].[ALBUMS_MEDIAS]    Script Date: 11/16/2014 20:08:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ALBUMS_MEDIAS](
	[ALBUMS_id] [bigint] NOT NULL,
	[medias_id] [bigint] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ALBUMS_MEDIAS]  WITH CHECK ADD  CONSTRAINT [FKC6B2D1CA4B3B4F81] FOREIGN KEY([ALBUMS_id])
REFERENCES [dbo].[ALBUMS] ([id])
GO

ALTER TABLE [dbo].[ALBUMS_MEDIAS] CHECK CONSTRAINT [FKC6B2D1CA4B3B4F81]
GO

ALTER TABLE [dbo].[ALBUMS_MEDIAS]  WITH CHECK ADD  CONSTRAINT [FKC6B2D1CABC976FEB] FOREIGN KEY([medias_id])
REFERENCES [dbo].[MEDIAS] ([id])
GO

ALTER TABLE [dbo].[ALBUMS_MEDIAS] CHECK CONSTRAINT [FKC6B2D1CABC976FEB]
GO

