USE [unitunes]
GO

/****** Object:  Table [dbo].[USER_FAVORITE_MEDIAS]    Script Date: 11/16/2014 20:08:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_FAVORITE_MEDIAS](
	[USER_ID] [bigint] NOT NULL,
	[MEDIA_ID] [bigint] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[USER_FAVORITE_MEDIAS]  WITH CHECK ADD  CONSTRAINT [FKB215409E74420F6] FOREIGN KEY([MEDIA_ID])
REFERENCES [dbo].[MEDIAS] ([id])
GO

ALTER TABLE [dbo].[USER_FAVORITE_MEDIAS] CHECK CONSTRAINT [FKB215409E74420F6]
GO

ALTER TABLE [dbo].[USER_FAVORITE_MEDIAS]  WITH CHECK ADD  CONSTRAINT [FKB215409E9BA489E] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([id])
GO

ALTER TABLE [dbo].[USER_FAVORITE_MEDIAS] CHECK CONSTRAINT [FKB215409E9BA489E]
GO

